version: '2' 
services: 
  db: 
    image: postgres 
    environment: 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD= 
    ports: 
      - '5432'
  web:
    build: . 
    command: bundle exec rails s -p 3000 -b '0.0.0.0' 
    volumes:
      - .:/ticketee 
    ports:
      - "3000:3000" 
    depends_on: 
      - db
  test:
    build: . 
    command: bundle exec rspec
    environment:
      - DISPLAY=unix$DISPLAY
    volumes:
      - .:/ticketee
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ports:
      - "3000:3000" 
    depends_on: 
      - db