version: '2' 
services: 
  db: 
    image: postgres 
    environment: 
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD= 
    ports: 
      - '5432'
  # selenium:
  #   image: selenium/standalone-firefox
  #   container_name: selenium 
  #   environment:
  #     - SELENIUM_REMOTE_HOST=selenium
  web: 
    build: . 
    command: bundle exec rails s -p 3000 -b '0.0.0.0' 
    volumes: 
      - .:/codemca 
    ports: 
      - "3000:3000" 
    depends_on: 
      - db
  # test:
  #   build: .
  #   command: bundle exec rspec
  #   volumes:
  #     - .:/codemca
  #   depends_on:
  #     - db
  #     - selenium